from __future__ import annotations
from pathlib import Path
from typing import Literal
from job_extractor import __version__
from job_extractor.models import CollectionResult
from job_extractor.reporting.field_formatters import locations_text,markdown_inline,scope_text
from job_extractor.reporting.summary import human_summary

class MarkdownReporter:
    def generate(self,result:CollectionResult,path:Path,detail:Literal["auto","compact","full"]="auto")->Path:
        mode=("full" if len(result.jobs)<=50 else "compact") if detail=="auto" else detail
        dc=result.data_completeness;m=result.metrics
        lines=["# Job Collection Report","","Generated by Job Extractor " + __version__,"","## Overview","",f"- Company: {markdown_inline(result.company or 'Unknown')}",f"- Platform: {markdown_inline(result.platform or 'Unknown')}",f"- Source: {markdown_inline(result.source_url)}",f"- Scope: {markdown_inline(scope_text(result.scope))}",f"- Collected at: {result.finished_at or result.started_at}","","## Collection Result","",f"- Expected: {result.total_expected}",f"- Fetched: {result.total_fetched}",f"- Unique: {result.total_unique}",f"- Status: {result.status}","","## Summary","",human_summary(result),"","## Data Quality","",f"- Complete: {dc.complete_jobs} / {dc.total_jobs}",f"- Missing JD: {dc.missing_jd_jobs}",f"- Missing Requirements: {dc.missing_requirements_jobs}",f"- Completeness: {dc.completeness_ratio:.1%}","","## Performance","",f"- Total Elapsed: {getattr(m, 'total_elapsed_seconds', None) or m.elapsed_seconds:.2f}s",f"- Collection Elapsed: {getattr(m, 'collection_elapsed_seconds', None) or m.elapsed_seconds:.2f}s",f"- Pages: {m.list_pages}",f"- List requests: {m.list_requests}",f"- Detail requests: {m.detail_requests}",f"- JD Strategy: {m.jd_strategy}","","## Warnings",""]
        lines.extend(f"- {markdown_inline(x)}" for x in result.warnings or ["None"])
        detail_audit=(result.enrichment or {}).get("detail_resolution") or {}
        if detail_audit:
            lines.extend(["","## Detail Resolution",""])
            labels=(
                ("detail_method", "Detail method"),
                ("rendered_page_attempted", "Rendered page attempted"),
                ("user_curl_attempted", "User Detail cURL attempted"),
                ("list_only_used", "List-only used"),
                ("jd_success", "JD success"),
                ("jd_failed", "JD failed"),
                ("jd_missing", "JD missing"),
            )
            lines.extend(f"- {label}: {markdown_inline(str(detail_audit[key]))}" for key,label in labels if key in detail_audit)
        if result.errors:lines.extend(["","## Errors",""]+[f"- {markdown_inline(x)}" for x in result.errors])
        lines.extend(["","## Jobs",""])
        if mode=="compact":lines.extend(["Full job descriptions are available in jobs.xlsx and jobs.json.",""])
        for i,job in enumerate(result.jobs,1):
            lines.extend([f"### {i}. {markdown_inline(job.job_title)}","",f"- Location: {markdown_inline(locations_text(job.locations) or 'Unknown')}",f"- Category: {markdown_inline(job.job_category or 'Unknown')}",f"- Department: {markdown_inline(job.department or 'Unknown')}",f"- Recruitment Type: {markdown_inline(job.recruitment_type or 'Unknown')}",f"- Detail: {markdown_inline(job.detail_url or '')}"])
            if mode=="full":
                jd=(job.full_jd or "No full JD available.").replace("```","` ` `")
                lines.extend(["","#### Full JD","","```text",jd,"```"])
            lines.append("")
        path.parent.mkdir(parents=True,exist_ok=True);path.write_text("\n".join(lines),encoding="utf-8");return path
